### ISSUE TITLE
easier definition for templating includes

### ISSUE THREAD

**Issue by nzar-tofiq** [BBCVisualJournalism/grunt-multi-lang-site-generator#8]
Two new behaviours
1. All but the testing files in the temp folder are converted into includes with a wild card maybe (this is to make it easier to include more "inc"s i the same iFrame)
2.A html or file name beginning with underscore is used for testing and includes all the newly created "inc" files.

**Comment by ChrisBAshton** [comment]
We now manage this internally with some custom Grunt code before passing the config to this module. Think these suggestions are outside of the remit of the module.
